### ISSUE TITLE
Using "rows" property on input component in Typescript

### ISSUE THREAD

**Issue by provarcher** [react-toolbox/react-toolbox#1183]
When I'm trying to use the "rows" property in my Typescript react project, it gives me an error saying that `[ts] Property 'rows' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & InputProps & { children?: {} | undefined; }'.`

![screen shot 2017-01-26 at 3 36 45 pm](https://cloud.githubusercontent.com/assets/20932095/22355076/59fc5564-e3dd-11e6-96bb-6be54b9ebaa4.png)

I have one idea of why this may be: in the definition for InputProps (in `react-toolbox/components/input/Input.d.ts`), rows is the only property without a space after the colon, and it's the only one giving me that error.

![screen shot 2017-01-26 at 3 32 25 pm](https://cloud.githubusercontent.com/assets/20932095/22355037/18555476-e3dd-11e6-8705-2a63f21d24bd.png)

If this is the problem, it would be very easy to fix!

**Comment by rubenmoya** [comment]
I could open a PR, are we sure that's the problem?

**Comment by provarcher** [comment]
No, I'm not sure it's the problem. It was just a possibility that jumped out at me. If it's not the problem, I would still very much appreciate a fix that would allow me to use this property!

**Comment by provarcher** [comment]
Wait, unless the rows property was added in the future version and isn't available in the stable version...I guess that would make more sense

**Comment by panjiesw** [comment]
It supposed to be working in `2.0.0-beta.5`. It's not merged yet to master. Have you tried it with that version?

![input ts](https://cloud.githubusercontent.com/assets/1451848/22382645/1ff4e1de-e4f9-11e6-9f00-9d8d47d5392c.png)

**Comment by provarcher** [comment]
Yes, using the old version was definitely my problem! Sorry, I didn't realize row definition was such a new feature. Thanks everyone for your responses!
